### ISSUE TITLE
list of variables not present in newly created ListBoxViews

### ISSUE THREAD

**Issue by alex-scp** [hpuhr/ATSDB#44]
when creating ListBoxViews the Variables list box is empty unlike the case of the default ListBoxView which has some meta variables already included.

is this the expected behaviour?

the list of variables is useful, to examine and export data from the database.
a template of variables, ex: the ones used for the default main window, to be added to each newly created ListBoxView would increase the usability of adding new views.

**Comment by hpuhr** [comment]
Yes that is as expected (but not optimal), but I'll add the most commonly used variables as default ones (they can be removed as wanted later):
* Time of Day
* Datasource
* Lat/Long
* Mode 3/A code
* Mode S TA
* Mode S Callsign

If you want to have other ones by default, please comment. I'll reflag this issue as enhancement.

**Comment by alex-scp** [comment]
I would also add:
- Mode C
- Track Number

**Comment by hpuhr** [comment]
Added all mentioned meta variables, including rec_num, to a new listboxview
