### ISSUE TITLE
Issue in the calculation of min/max of table atsdb_minmax

### ISSUE THREAD

**Issue by alex-scp** [hpuhr/ATSDB#61]
The calculation seems not to take into account the records containing empty values.

The following is a picture of the atsdb_minmax table in such a case (highlighted fields have no value for max) :
![atsdb_minmax problem](https://user-images.githubusercontent.com/36778712/37870670-b43d0dc8-2fd3-11e8-9d27-a5817fd2ec3e.png)

The following is a view of the CSV file used to calculate the values of the above table:
![atsdb_minmax problem table](https://user-images.githubusercontent.com/36778712/37870738-a3fcd348-2fd4-11e8-9c11-b9e30c36beb4.png)

When not having valid maximum values in the atsdb_minmax table the ATSDB crashes.

ATSDB doesn't seem to crash when the minimum value is not calculated.

**Comment by alex-scp** [comment]
The calculation of min also seems to be affected by the records containing empty values.
The case of CALLSIGN above is an example.

**Comment by hpuhr** [comment]
Is this happening only in SQLite3 (my assumption) or also in MySQL?

**Comment by alex-scp** [comment]
I've only seen this behaviour with sqlite after converting a CSV file.
Still to be tested with MySQL.

**Comment by hpuhr** [comment]
I reviewed the issue, the application was not expecting empty min/max strings, which occur then "empty" values are not inserted as SQL NULL values but empty values ''.
Removed the assert, still applications should use the NULL values instead.
