### ISSUE TITLE
Review prepADSBxchg DateTime.pm issue

### ISSUE THREAD

**Issue by hpuhr** [hpuhr/ATSDB#64]
Fails now with the error:
"Can't locate DateTime.pm in @INC (you may need to install the DateTime module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.0 /usr/local/share/perl/5.26.0 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/sk/bin/parseADSBxchg line 54.
BEGIN failed--compilation aborted at /home/sk/bin/parseADSBxchg line 54.
grep: ADS-B/*.csv: No such file or directory"

I tried to install it using:
"
$ perl -MCPAN -e shell
cpan> install DateTime
cpan> q
"
but it still gives the same error. Also the installation took very long, but since I do know little about perl I don't know how to continue?

**Comment by alex-scp** [comment]
problem solved, documentation updated.
