### ISSUE TITLE
issue when having less than four sources

### ISSUE THREAD

**Issue by alex-scp** [hpuhr/ATSDB#72]
when having less than four sources: MLAT, ADS-B, radar and tracker in the evaluation a crash occurs.

the following is the log of such an occurrence with only one ADS-B source.
[less-than-four-sources.problem.log](https://github.com/hpuhr/ATSDB/files/1964538/less-than-four-sources.problem.log)

**Comment by hpuhr** [comment]
Unable to reproduce with the current version. Hopefully fixed. Please reopen if still encountered.
